### ISSUE TITLE
 Unable to access jarfile ./jd-cli.jar

### ISSUE THREAD

**Issue by FrancisShi** [lxdvs/apk2gold#18]
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/Francis/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0101048f
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:107)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:91)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:322)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:123)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:86)
mv: rename Test/smali to Test/.smali: No such file or directory
dex2jar Test.apk -> Test-dex2jar.jar
Converting .class files to java...
Error: Unable to access jarfile ./jd-cli.jar
Reassociated 0 R.* references in 0 files

**Comment by oximer** [comment]
same error

**Comment by jaredsburrows** [comment]
@FrancisShi You need to run ./make.sh, first
